export const ADD_BOOKING_REQUEST = 'ADD_BOOKING_REQUEST'
export const ADD_BOOKING_FAIL = 'ADD_BOOKING_FAIL'

export const CONFIRM_BOOKING_REQUEST = 'CONFIRM_BOOKING_REQUEST'
export const CONFIRM_BOOKING_FAIL = 'CONFIRM_BOOKING_FAIL'

export const MY_BOOKINGS_SUCCESS = 'MY_BOOKINGS_SUCCESS'
export const MY_BOOKINGS_FAIL = 'MY_BOOKINGS_FAIL'