export const ALL_LANDING_REQUEST = "ALL_LANDING_REQUEST";
export const ALL_LANDING_SUCCESS = "ALL_LANDING_SUCCESS"
export const ALL_LANDING_FAIL = "ALL_LANDING_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"