export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS"
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL"

export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS"
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL"

export const OWNER_ROOMLIST_REQUEST = "OWNER_ROOMLIST_REQUEST"
export const OWNER_ROOMLIST_SUCCESS = "OWNER_ROOMLIST_SUCCESS"
export const OWNER_ROOMLIST_FAIL = "OWNER_ROOMLIST_FAIL"

export const NEW_ROOM_REQUEST = "NEW_ROOM_REQUEST"
export const NEW_ROOM_SUCCESS = "NEW_ROOM_SUCCESS"
export const NEW_ROOM_RESET = "NEW_ROOM_RESET"
export const NEW_ROOM_FAIL = "NEW_ROOM_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"