export const WATCHLIST_ADD_ROOM = "WATCHLIST_ADD_ROOM";
export const WATCHLIST_REMOVE_ROOM = "WATCHLIST_REMOVE_ROOM";
export const WATCHLIST_CLEAR_ROOM = "WATCHLIST_CLEAR_ROOM";

export const ALL_WATCHLIST_SUCCESS = "ALL_WATCHLIST_SUCCESS"
export const ALL_WATCHLIST_FAIL = "ALL_WATCHLIST_FAIL"